cgserver/cgserver/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, reverse

urlpatterns = [
    path('', lambda request: redirect(reverse('serverlist:index')), name='index'),
    path('admin/', admin.site.urls),
    path('serverlist/', include('serverlist.urls')),
]

cgserver/serverlist/urls.py
from django.urls import path

from . import views

app_name = 'serverlist'

urlpatterns = [
    path('', views.index, name='index'),
    path('', views.index, name='loginrequired'),
    path('client/<int:pk>', views.client, name='client'),
    path('client/<int:pk>/chart', views.clientchart, name='clientchart'),
    path('client/<int:client_id>/report/<int:report_id>', views.clientreport, name='clientreport'),
    path('clientreport', views.recvreport),
    path('profile', views.profile, name='profile'),
    path('vpn', views.vpn, name='vpn'),
    path('pptp', views.pptp, name='pptp'),
    path('ftp', views.ftp, name='ftp'),
    path('latex', views.latex, name='latex'),
    path('nas', views.nas, name='nas'),
    path('download', views.download, name='download'),
    path('login', views.loginpassword, name='loginpassword'),
    path('logingithuboauth', views.logingithuboauth, name='logingithuboauth'),
    path('githubcallback', views.githubcallback, name='githubcallback'),
    path('opencheckuser', views.opencheckuser, name='opencheckuser'),
    path('vpnauth', views.vpnauth, name='vpnauth'),
    path('ftpauth', views.ftpauth, name='ftpauth'),
    path('ftpinsecurecheck', views.ftpinsecurecheck, name='ftpinsecurecheck'),
    path('cgnas_api', views.cgnas_api, name='cgnas_api'),
    path('radius_api', views.radius_api, name='radius_api'),
    path('resetpassword', views.resetpassword, name='resetpassword'),
    path('logout', views.logout, name='logout'),
]

cgserver/serverlist/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Username',
            },
        ),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
            },
        ),
    )


class ResetPasswordForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Username',
            },
        ),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
            },
        ),
    )


class FtpForm(forms.Form):
    action = forms.CharField()
    id = forms.IntegerField(required=False)
    username = forms.CharField(required=False)
    path = forms.CharField(required=False)
    isdir = forms.BooleanField(required=False)
    permission = forms.CharField(required=False)

cgserver/serverlist/views.py
import base64
import boto3
import crypt
import functools
import ipaddress
import json
import pprint
import requests
import threading
import time
import uuid

from .forms import LoginForm, ResetPasswordForm, FtpForm
from .models import AccessLog, Client, ClientReport, Employee, FtpPerm, GithubUser, UnknownReport
from datetime import datetime, timedelta
from django.conf import settings
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import models, transaction
from django.db.models import Max
from django.http import Http404, HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from helper import md4
from six.moves import urllib
from socket import AddressFamily

# Create your views here.

def get_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        return x_forwarded_for.split(',')[0]
    else:
        return request.META.get('REMOTE_ADDR')

def is_tsinghua_ip(ip):
    addr = ipaddress.ip_address(ip)
    return addr.is_private or \
        any(addr in ipaddress.ip_network(net) for net in (
            '59.66.0.0/16',
            '101.5.0.0/16',
            '101.6.0.0/16',
            '118.229.0.0/19',
            '166.111.0.0/16',
            '183.172.0.0/15',
            #'219.223.168.0/21', # Shenzhen
            #'219.223.176.0/20', # Shenzhen
        ))

def get_mac(report, ip):
    for if_addr in report['net_if_addrs'].values():
        internet_interface = False
        for snicaddr in if_addr:
            if snicaddr[0] in (AddressFamily.AF_INET, AddressFamily.AF_INET6) and snicaddr[1] == ip:
                internet_interface = True
        if internet_interface:
            for snicaddr in if_addr:
                if snicaddr[0] == 17 or snicaddr[0] == -1 and 17 == len(snicaddr[1]):  # psutil.AF_LINK is 17 on Linux, and it is -1 on Windows
                    return snicaddr[1]
    return None

def has_access(user):
    if not user.is_anonymous and hasattr(user, 'employee') and user.employee.can_access:
        if not user.employee.staff_number:
            user.employee.staff_number = 1 + (Employee.objects.all().aggregate(Max('staff_number'))['staff_number__max'] or 0)
            user.employee.save()
        return True
    return False

def check_access(func):
    @functools.wraps(func)
    def _decorator(request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect(reverse('serverlist:loginrequired'))
        elif has_access(request.user):
            return func(request, *args, **kwargs)
        else:
            if not hasattr(request.user, 'employee'):
                Employee.objects.create(user=request.user)
            return redirect(reverse('serverlist:profile'))
    return _decorator

def index(request):
    if request.user.is_anonymous:
        return render(request, 'serverlist/loginrequired.html')
    elif not has_access(request.user):
        return redirect(reverse('serverlist:profile'))

    client_reports = ClientReport.objects.values('client_id').annotate(id=models.Max('id'))
    clients_no_report = Client.objects.exclude(id__in=[c['client_id'] for c in client_reports]).filter(priority__lt=99).order_by('priority', 'client_id')
    client_reports = ClientReport.objects.filter(id__in=[c['id'] for c in client_reports], client__priority__lt=99).select_related('client').order_by('client__priority', 'client__client_id')
    now = time.time()
    table = []
    for client_report in client_reports:
        client = client_report.client
        report = json.loads(client_report.report)
        status = 'ok'
        if client_report.version not in ('0.1.2', '0.1.3'):
            status = '版本不匹配'
            platform = ''
        elif report['uname'][0] == 'Linux':
            platform = '{:s} {:s}'.format(report['dist'][0].capitalize(), report['dist'][1])
        elif report['uname'][0] == 'Windows':
            platform = 'Windows {:s}'.format(report['uname'][2])
        else:
            platform = report['uname'][0]
        tr = []
        tr.append(client.display_name or client.client_id)
        tr.append(platform)
        ips = [client_report.ip]
        if settings.ROUTE53_DOMAIN_NAME:
            ips.append(client.client_id.lower() + '.' + settings.ROUTE53_DOMAIN_NAME)
        mac = get_mac(report, client_report.ip)
        if mac:
            ips.append(mac)
        tr.append(ips)
        if status == 'ok':
            tr.append([
                    ('{:d} 核 '.format(report['cpu_count_physical']) if 'cpu_count_physical' in report else '') + \
                    '{:d} 线程'.format(report.get('cpu_count_logical', report.get('cpu_count'))),
                    '使用率 {:.0f}%'.format(report['cpu_percent']),
                    '最高频率 {:.1f}GHz'.format(report['cpu_freq'][2] / 1000),
                ])
            tr.append('N/A' if report['loadavg'] is None else '{:.1f}'.format(report['loadavg'][2]))
            tr.append('{:.1f}G ({:.0f}%)'.format(report['virtual_memory'][0] / 1024 ** 3, report['virtual_memory'][2]))
            disks = list(zip(report['disk_partitions'], report['disk_usage']))
            disks.sort(key=lambda a: (a[0][0], -a[1][0]))
            disks = [usage for i, (partition, usage) in enumerate(disks) if partition[0] not in set(p[0] for p, _ in disks[:i])]
            tr.append(['{:.0f}G ({:.0f}%)'.format(disk[0] / 1024**3, disk[3]) for disk in disks if disk[0] / 1024**3 > 9])
            if report['nvml_version']:
                tr.append([dev['nvmlDeviceGetName'] if dev else 'GPU{:d} is lost'.format(i) for i, dev in enumerate(report['nvmlDevices'])])
                tr.append(['{:.1f}G ({:.0f}%)'.format(
                        dev['nvmlDeviceGetMemoryInfo']['total'] / 1024**3,
                        dev['nvmlDeviceGetMemoryInfo']['used'] / dev['nvmlDeviceGetMemoryInfo']['total'] * 100,
                    ) if dev else '-' for dev in report['nvmlDevices']])
                tr.append(['{:s}% {:.0f}W {:d}℃'.format(
                        '-' if dev['nvmlDeviceGetUtilizationRates']['gpu'] is None else '{:d}'.format(dev['nvmlDeviceGetUtilizationRates']['gpu']),
                        dev['nvmlDeviceGetPowerUsage'] / 1000,
                        dev['nvmlDeviceGetTemperature'],
                    ) if dev else '-' for dev in report['nvmlDevices']])
            else:
                tr.append('NVML failed')
                tr.append('N/A')
                tr.append('N/A')
            users = [user[0] for user in report['users']]
            users = sorted(list(set(users)))
            if len(users) > 4:
                users = users[:3] + ['...']
            tr.append(users)
            tr.append('{:.0f} 天'.format((now - report['boot_time']) / 86400, 0))
            dt = now - client_report.created_at.timestamp()
            if dt >= 86400:
                tr.append([
                    '{:.0f} 分钟前'.format(dt / 60),
                    '({:.1f} 天前)'.format(dt / 86400),
                ])
            else:
                tr.append('{:.0f} 分钟前'.format(dt / 60))
        else:
            tr += [''] * 9
            tr.append(status)
        tr.append([client.info, client.manager])
        table.append({'client': client, 'tr': tr})
    for client in clients_no_report:
        tr = []
        tr.append(client.client_id)
        tr.append('N/A')
        tr.append('N/A')
        tr += [''] * 9
        tr += ['未配置']
        tr.append([client.info, client.manager])
        table.append({'client': client, 'tr': tr})
    AccessLog.objects.create(user=request.user, ip=get_ip(request), target='serverlist:index')
    return render(request, 'serverlist/index.html', {'table': table})

@check_access
def client(request, pk):
    client = get_object_or_404(Client.objects, pk=pk)
    client_reports = ClientReport.objects.filter(client=client).order_by('-id')
    paginator = Paginator(client_reports, 100)
    client_reports = paginator.get_page(request.GET.get('page'))
    AccessLog.objects.create(user=request.user, ip=get_ip(request), target='serverlist:client', param=pk)
    return render(request, 'serverlist/client.html', {'client': client, 'client_reports': client_reports})

@check_access
def clientchart(request, pk):
    client = get_object_or_404(Client.objects, pk=pk)
    client_reports = ClientReport.objects.filter(client=client).filter(created_at__gt=timezone.now() - timedelta(days=7)).order_by('-created_at')
    data = []
    for report in client_reports:
        day = (report.created_at.timestamp() - timezone.now().timestamp()) / 86400.
        report = json.loads(report.report)
        data.append({
            'day': day,
            'cpu': report['cpu_percent'],
            'virtual_memory': report['virtual_memory'][2],
            'gpu': [{
                'name': dev['nvmlDeviceGetName'],
                'util': dev['nvmlDeviceGetUtilizationRates']['gpu'],
                'memory': dev['nvmlDeviceGetMemoryInfo']['used'] / dev['nvmlDeviceGetMemoryInfo']['total'] * 100,
                'temperature': dev.get('nvmlDeviceGetTemperature', None),
            } if dev else None for dev in report.get('nvmlDevices', [])],
        })
    AccessLog.objects.create(user=request.user, ip=get_ip(request), target='serverlist:clientchart', param=pk)
    return render(request, 'serverlist/clientchart.html', {'client': client, 'data': base64.b64encode(json.dumps(data, ensure_ascii=True).encode()).decode()})

@check_access
def clientreport(request, client_id, report_id):
    client_report = get_object_or_404(ClientReport.objects.select_related('client'), id=report_id, client_id=client_id)
    report = json.loads(client_report.report)
    mac = get_mac(report, client_report.ip)

cgserver/serverlist/templates/serverlist/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}CG Server{% endblock %}</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="shortcut icon" href="{% static 'serverlist/G2.ico' %}">
		{% block head %}{% endblock %}
		<link href="{% static 'serverlist/bootstrap.min.css' %}" rel="stylesheet">
		<style>{% include "./nav.css" %}</style>
	</head>
	<body>
		{% include "./nav.html" %}
		{% block container %}
		<div class="container mt-4 mb-5">
			{% block content %}{{ content }}{% endblock %}
		</div>
		{% endblock %}
		{% include "./footer.html" %}
		<script src="{% static 'serverlist/jquery-3.3.1.slim.min.js' %}"></script>
		<script src="{% static 'serverlist/bootstrap.min.js' %}"></script>
	</body>
</html>

cgserver/serverlist/templates/serverlist/download.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class="mb-4">离线下载</h1>
<p><b>网址</b>（校内访问优化）<a href="https://www.thucg.com/download9/">www.thucg.com/download9</a></p>
<p><b>网址</b>（用于校外访问）<a href="https://cg.cs.tsinghua.edu.cn/download9/">cg.cs.tsinghua.edu.cn/download9</a></p>
<hr>

<h3>FAQ</h3>
<p>
	Q: 技术信息<br>
	A: CG Download 修改自计算机系科协的 <a href="https://git.net9.org/sast/Download9">Download9</a><br>
	A: 如果你有 Account9 帐号，还可以使用新版 <a href="https://download.net9.org/">科协 Download9</a>
</p>
<p>
	Q: 免流量吗？<br>
	A: 是。离线下载服务开在 68.30 服务器上
</p>
<p>
	Q: 技术上无法下载什么？<br>
	A: 无法下载需要登录才能下载的文件、需要 cookie 才能下载的文件、需要辨别浏览器标识才能下载的文件
</p>
{% endblock %}

cgserver/serverlist/templates/serverlist/loginpassword.html
{% extends "./base.html" %}

{% block content %}
<h1 class="mb-4">登入 - 验证密码</h1>
<div class="col-sm-12 col-md-6 pb-5">
	<form method="post" role="form">
		{% csrf_token %}
		<p>
			<label>用户名</label>
			{{ form.username }}
			{{ form.username.errors }}
		</p>
		<p>
			<label>密码</label>
			{{ form.password }}
			{{ form.password.errors }}
		</p>
		<p>
			<input type="submit" class="form-control btn btn-primary" value="登入">
		</p>
		<p class="text-right">
			忘记密码？<a href="{% url 'serverlist:logingithuboauth' %}">通过 GitHub 授权</a>
		</p>
	</form>
</div>
{% endblock %}

cgserver/serverlist/templates/serverlist/loginrequired.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Account status{% endblock %}

{% block content %}
<h1 class="mb-4">需要登录</h1>
<p>请 <a href="{% url 'serverlist:loginpassword' %}">验证密码</a> 或 <a href="{% url 'serverlist:logingithuboauth' %}">通过 GitHub 授权</a> <img src="{% static 'serverlist/GitHub-Mark-32px.png' %}" style="height: 1em;" alt="GitHub mark">。</p>
{% endblock %}

cgserver/serverlist/templates/serverlist/nas.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class="mb-4">存储空间（Network Attached Storage）</h1>
<p><b>服务器：</b><a href="http://nas.thucg.com/">nas.thucg.com</a></p>
<p><b>帐号：</b>使用本网站的<a href="{% url 'serverlist:profile' %}">用户名和密码</a></p>
<p><b>UID：</b>{{ uid }}</p>
<p>
	<b>个人目录:</b>
	<br>
	<ul>
		<li>/home/{{ user.username }} (软链接，指向 {{ home }})</li>
		<li>{{ home }} (<b>home 目录</b>，RAID6) 存放存档数据</li>
		<li>/nas/disk-0/{{ uid }} (non-RAID) 暂时存放高频读写数据</li>
		<li>/nas/disk-1/{{ uid }} (non-RAID) 暂时存放高频读写数据</li>
	</ul>
</p>
<p>默认权限：<code>drwxr-x---</code>，自己可读写，其它登录用户只读，NFS 无访问权限</p>
<p>隐私权：管理员不查看用户文件的内容，但是会查看文件的元数据（文件名、大小等）</p>

<hr>

<h3>提供 3 种访问方式</h3>
<h3>1. ssh / SFTP</h3>
<p>
	服务器公钥指纹：<br>
	<code class="ml-3" style="color: #212529;">2048 SHA256:2P8LqYgxCdZz0tT2+rFkmGcOLl2MkiEXjhOydid2dgY (RSA)</code><br>
	<code class="ml-3" style="color: #212529;">256 SHA256:PxnQCIMJgd0LvVjKUei6YooVYTgkFk05pVccKSfmvGg (ECDSA)</code><br>
	<code class="ml-3" style="color: #212529;">2048 1d:ff:ad:16:ba:96:b1:74:69:66:e5:f2:43:6f:d0:14 (RSA)</code><br>
	<code class="ml-3" style="color: #212529;">256 85:53:11:b0:18:f4:9d:84:3e:05:07:7f:22:2f:d3:e8 (ECDSA)</code><br>
	登录：<code>$ ssh {{ user.username }}@nas.thucg.com</code><br>
	登录时公钥指纹<strong class="text-danger">必须</strong>与以上指纹中的一个相同，否则<strong class="text-danger">必须</strong>停止登录<br>
	sshfs 挂载命令：<code>$ sshfs -oreconnect,ServerAliveInterval=15,ServerAliveCountMax=3 {{ user.username }}@nas.thucg.com: /path/to/mount</code><br>
	sshfs 卸载命令：<code>$ fusermount -u /path/to/mount</code><br>
	只能在本网站修改用户名和密码，无法用 passwd 修改密码<br>
	警告：删除挂载点时请使用 <code>$ rmdir /path/to/mount</code>，不要用 rm -r。因为万一没有卸载，rm -r 会递归删除 NAS 上的数据，而 rmdir 不会<br>
</p>

<h3>2. Windows 映射网络驱动器</h3>
<p>
	“我的电脑”->“映射网络驱动器”，“网络位置”（或“文件夹”）填 <code>\\nas.thucg.com\share</code>，使用本网站的<a href="{% url 'serverlist:profile' %}">用户名和密码</a>登录<br>
	注意：1) 两种系统对文件名大小写的敏感性不同，如果同时有 abc 和 ABC 两个文件，可能会出错。 2) 软链接会被当作文件夹，可能导致文件路径无限递归<br>
</p>

<h3>3. nfs</h3>
<p>
	先安装 <code># apt install nfs-common</code><br>
	方法一、通过 fstab 挂载：往 /etc/fstab 加一行 <code>nas.thucg.com:/	/path/to/mount	nfs	nosuid,nodev	0	0</code>，然后 <code># mount /path/to/mount</code>，重启会自动挂载<br>
	方法二、手动挂载一次：<code># mount -tnfs -onosuid,nodev nas.thucg.com:/ /path/to/mount</code><br>
	卸载命令：<code># umount /path/to/mount</code><br>
	必须开启 nosuid,nodev 选项以增加安全性<br>
	nfs 无法做用户身份验证，安全起见，所有用户都映射为 <code>nobody:nogroup</code><br>
	如需 NFS 可读取自己的 home 目录，执行 <code>$ chmod 755 {{ home }}</code><br>
	如需 NFS 可写入 some-dir，执行 <code>$ chmod 1777 {{ home }}/some-dir</code><br>
	警告：删除挂载点时请使用 <code>$ rmdir /path/to/mount</code>，不要用 rm -r。因为万一没有卸载，rm -r 会递归删除 NAS 上的数据，而 rmdir 不会<br>
</p>

<h3>FAQ</h3>
<p>
	Q: 保存哪些目录？<br>
	A: 只有 <code>/nas</code> 下的文件会保存，其它目录（例如 <code>/tmp</code>、<code>/etc</code>、<code>/home</code>、<code>/usr</code>）会在服务重启时重置<br>
	A: 如果你的文件大小超过 4 TB，或者文件数量超过 10,000,000 个，我们可能会要求你清理
</p>
<p>
	Q: 密码错误<br>
	A: 请在 <a href="http://nas.thucg.com/">nas.thucg.com</a> 查看服务目前的状态，有可能你的用户名不满足要求（例如 root、nobody 等系统帐号），或者出现了其它错误<br>
	A: 因为帐号是根据网站用户动态设置的，所以只能在本网站设置密码，没法用 passwd 命令设置
</p>
<p>
	Q: 服务器连了外网吗？<br>
	A: 已通过 OpenVPN 接到 6830，可以上网。因此你可以直接在 NAS 上下载数据，也可以在 ssh 里执行数据解压等其它命令
</p>
<p>
	Q: 在校外如何访问 NAS？<br>
	A: 请看如何通过 <a href="{% url 'serverlist:vpn' %}">OpenVPN</a> 访问校内资源
</p>
<p>
	Q: 数据备份<br>
	A: 没有数据备份机制，文件系统安全性由 Linux 权限机制保证，泄漏帐号导致的数据丢失无法恢复<br>
	A: <code>/nas/raid</code> 由冗余磁盘阵列 RAID6 提供冗余，<code>/nas/disk-0</code>、<code>/nas/disk-1</code> 为非 RAID
</p>
{% endblock %}

cgserver/serverlist/templates/serverlist/nav.html
{% load static %}
{% load serverlisttags %}
<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar" style="background-color: #743481;">
	<a class="navbar-brand d-none d-md-block mr-0 mr-md-2" href="{% url 'serverlist:index' %}">CSCG</a>
	<div class="navbar-nav-scroll">
		<ul class="navbar-nav">
			<li class="nav-item"><a class="nav-link{% eqorno request.resolver_match.url_name 'index'    ' active' '' %}" href="{% url 'serverlist:index' %}">ServerList</a></li>
			{% if user.employee.can_access %}
			<li class="nav-item"><a class="nav-link{% eqorno request.resolver_match.url_name 'vpn'      ' active' '' %}" href="{% url 'serverlist:vpn' %}">OpenVPN</a></li>
			<li class="nav-item"><a class="nav-link{% eqorno request.resolver_match.url_name 'pptp'     ' active' '' %}" href="{% url 'serverlist:pptp' %}">PPTP</a></li>
			<li class="nav-item"><a class="nav-link{% eqorno request.resolver_match.url_name 'ftp'      ' active' '' %}" href="{% url 'serverlist:ftp' %}">FTP</a></li>
			<li class="nav-item"><a class="nav-link{% eqorno request.resolver_match.url_name 'latex'    ' active' '' %}" href="{% url 'serverlist:latex' %}">LaTeX</a></li>
			<li class="nav-item"><a class="nav-link{% eqorno request.resolver_match.url_name 'nas'      ' active' '' %}" href="{% url 'serverlist:nas' %}">NAS</a></li>
			<li class="nav-item"><a class="nav-link{% eqorno request.resolver_match.url_name 'download' ' active' '' %}" href="{% url 'serverlist:download' %}">Download</a></li>
			{% endif %}
		</ul>
	</div>
	<ul class="navbar-nav flex-row ml-md-auto d-md-flex">
		{% if user.is_anonymous %}
		<li class="nav-item dropdown">
			<a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Anonymous user </a>
			<div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
				<a class="dropdown-item" href="{% url 'serverlist:loginpassword' %}">Login with password</a>
				<a class="dropdown-item" href="{% url 'serverlist:logingithuboauth' %}">Login with GitHub OAuth <img src="{% static 'serverlist/GitHub-Mark-32px.png' %}" style="height: 1em;" alt="GitHub mark"></a>
			</div>
		</li>
		{% else %}
		<li class="nav-item dropdown">
			<a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }} </a>
			<div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
				<a class="dropdown-item" href="{% url 'serverlist:profile' %}">Profile</a>
				<div class="dropdown-divider"></div>
				<form action="{% url 'serverlist:logout' %}" method="post">
					{% csrf_token %}
					<input class="dropdown-item" style="cursor: pointer;" type="submit" value="Logout">
				</form>
			</div>
		</li>
		{% endif %}
	</ul>
</header>

cgserver/serverlist/templates/serverlist/profile.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Account status{% endblock %}

{% block content %}

{% if user.employee.can_access %}
<h1 class="mb-4">Profile</h1>
<p><b>Username:</b> <span>{{ user.username }}</span> | <a href="{% url 'serverlist:resetpassword' %}">change username</a></p>
<p><b>Email:</b> <span>{{ user.email }}</span></p>
{% if password_set %}
<p><b>Password:</b> *** (don't use GitHub password) | <a href="{% url 'serverlist:resetpassword' %}">reset password</a></p>
<p><b>Password updated at:</b> {{ user.employee.password_updated_at | date:'Y-m-d H:i:s' }}</p>
{% else %}
<p><b>Password:</b> <i style="color: red">has not been set</i> | <a href="{% url 'serverlist:resetpassword' %}">reset password</a></p>
{% endif %}
{% else %}
<h1 class="mb-4">Profile (inactive)</h1>
<p><b>Username:</b> <span>{{ user.username }}</span></p>
<p><b>Email:</b> <span>{{ user.email }}</span></p>
<p>Please notify administrator to activate your account.</p>
<p>If you have just joined <a href="https://github.com/thucg">github.com/thucg</a>, please logout and login again.</p>
{% endif %}

<p>Inspect your GitHub authorization? Click <a href="https://github.com/settings/connections/applications/{{ GITHUB_CLIENT_ID }}">here</a>.</p>
{% endblock %}